### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by 1gnoramus** [1gnoramus/dota_warding_stats#4]
I have problem with testing an app: it can send appr. 30 requests/minute. I think there is a limit in sending request, so i have to hot restart the page. But it doesn't work everytime too, so i wonder if there is any solutions to this problem. I surely can make moke arrays and so one, but i want to test it in real database

**Comment by 1gnoramus** [comment]
I just killed a moscito and it's still alive wtf

**Comment by 1gnoramus** [comment]
AND I HAVE A BIG BUG IN MY ROOM WTF?AM IN ANIMAL PLANETS OR SOME SHIT
*pinned a picture for you to judge if its big enough (for comparison drew approx sizes of my hand and my penus)*

![BUG problem he he](https://github.com/1gnoramus/dota_warding_stats/assets/98352186/9fd70836-8834-490c-80f2-3014b5f63fa8)

**Comment by 1gnoramus** [comment]
![REAL BIG FUCKING BUG REAL ONLINE NO REGISTRATION picture](https://github.com/1gnoramus/dota_warding_stats/assets/98352186/29b30fcd-a649-4030-bbf1-cce5de0baf8b)

Here's a real picture if this insect

**Comment by bl1nkker** [comment]
@1gnoramus 

First we need to implement the main functionality (displaying wards on a heat map). After this, you can optimize the number of requests using an additional server and caching service. I'll think about its implementation
